### PR TITLE
feature: added powershell icon

### PR DESCRIPTION
**Pull request by nikolovlazar**
Added a powershell icon. Need this for [Sentry Answers](https://sentry.io/answers).

### CODE REVIEW

**Comment by nikolovlazar** [comment]
I'll put this under "Windows"

**Comment by bruno-garcia** [comment]
@nikolovlazar any chance we can get this in? We can use it on the docs and wizard: https://github.com/getsentry/sentry-powershell/

**Comment by bruno-garcia** [comment]
also, powershell (core) is cross platform, I use it on a mac :)

**Comment by nikolovlazar** [comment]
@Jesse-Box do you mind doing the dark mode thing on this icon?

**Comment by Jesse-Box** [comment]
Here you go mate

the file name indicates which directory they need to be in 

powershell-80
powershell-20

**Comment by bruno-garcia** [comment]
wooo! thanks Jesse!

**Pull request merged**
