### PR TITLE
Remove background fill from rust.svg

### PR DESCRIPTION
**Pull request by MaxBittker**
:crab:

### CODE REVIEW

**Comment by MaxBittker** [comment]
oh, on second look they're supposed to have background fills

**Comment by MaxBittker** [comment]
image

it does look weird in the UI though against a similar but slightly different color

**Comment by MaxBittker** [comment]
LBPhJQivzx9

Ok, this time I tried changing it to the color that github uses for rust, but no sweat if you don't want to merge this, the current color is fine

**Comment by ckj** [comment]
Missed this @MaxBittker. Also: hi!

**Pull request merged**
