### PR TITLE
Add fastapi icons

### PR DESCRIPTION
**Pull request by targhs**
Update for #56

### CODE REVIEW

**Comment by doralchan** [comment]
Thanks! The smaller one will need a background for better visibility. Here's the SVG

**20x20**
fastapi_20x20

Here's the optimized version of the large one as well. 

**80x80**
fastapi_80x80

**Review by doralchan — CHANGES_REQUESTED** [review]
Thanks! The smaller one will need a background for better visibility (similar to all the other logos in this size). Here's the SVG

**20x20**


Here's the optimized version of the large one as well. 

**80x80**

**Comment by targhs** [comment]
Am I missing any requested change?

**Comment by HazAT** [comment]
By now we have it already, thank you

**Pull request closed without merging**
