### PR TITLE
Add Qt icon native platform alias

### PR DESCRIPTION
**Pull request by torarnv**

### CODE REVIEW

**Comment by torarnv** [comment]
@bruno-garcia

**Comment by torarnv** [comment]
Removed the changes to the HTML, so all is left is the qt icon alias

**Review by bruno-garcia — APPROVED** [review]

**Comment by matejminar** [comment]
@torarnv Thank You! 🚀

**Comment by torarnv** [comment]
Cheers @matejminar ! If you push a version bump we can update sentry-doc and make the icon live on docs.sentry.io Thanks!

**Pull request merged**
