### PR TITLE
ref(update-logos): replacing svgs

### PR DESCRIPTION
**Pull request by doralchan**
**Logo Update**

- Replaces old logos with new logos
- Replaces old AI files with new integration and platform AI files

Screen Shot 2020-09-01 at 3 52 13 PM
Screen Shot 2020-09-01 at 3 52 06 PM

### CODE REVIEW

**Comment by dcramer** [comment]
lgtm only concern would be if theres any raw usage that relies on the implicit size specified in the svgs

**Comment by bruno-garcia** [comment]
I'm probably the most excited about this change

**Review by matejminar — CHANGES_REQUESTED** [review]
Hey, do we realize that this is kind of a **breaking change**?

If we publish this and update `platformicons` package in sentry's `package.json`, we will show these new logos everywhere in the product.

For example here:

image
also, issues stream, releases, discover, projects, you get the point.

Most of these places assume that the icon is readable in a very small format and has a colored background.

Node is a good example, this is the old one:

image

and if we were to publish this, it would get replaced with this one (not ideal for displaying in a small 16x16 square):

image

I know that you also created this version of icons:

screen_shot_2020-08-31_at_5 52 12_pm

Would it make sense to add colored background and upload these into `svg` folder instead?

And for new high fidelity official logos, we could create a `logos` folder or something.

**Comment by doralchan** [comment]
@matejminar this doesn't replace the existing icon font or the usage of the icon font. It's only replacing the svgs that are already in there so it's quickly accessible.

**Comment by matejminar** [comment]
But those svgs in the `svg` folder you are replacing are the ones that are used in the app.

The only place that's using the old **icon font** is this page:
image

**Pull request closed without merging**
